from __future__ import annotations

import re


PREAMBLE_RE = re.compile(
    r"^\s*(absolument|bien sûr|bien sur|certainement|voici|d'accord|daccord|"
    r"sure|certainly|of course|here is|here are|okay|ok|"
    r"natürlich|hier ist|hier sind|claro|por supuesto|aquí está|aqui esta)\b",
    re.IGNORECASE,
)


def _clean_formula_markup(text: str) -> str:
    """Make common LLM/LaTeX-ish formulas readable in plain PDF text."""
    text = text.replace("$", "")
    text = text.replace("\\rightarrow", "→")
    text = text.replace("\\to", "→")
    text = text.replace("\\cup", "∪")
    text = text.replace("\\cap", "∩")
    text = text.replace("\\subseteq", "⊆")
    text = text.replace("\\ge", ">=")
    text = text.replace("\\le", "<=")
    text = text.replace("\\times", "×")
    text = text.replace("\\text", "")
    text = re.sub(r"\\sum_?\{?([^}]*)\}?", r"Σ\1", text)
    text = re.sub(r"\\log_?\{?2\}?", "log2", text)

    # Simple \frac{a}{b} -> (a) / (b). This intentionally avoids complex nested parsing.
    frac_pattern = re.compile(r"\\frac\{([^{}]+)\}\{([^{}]+)\}")
    while True:
        updated = frac_pattern.sub(r"(\1) / (\2)", text)
        if updated == text:
            break
        text = updated

    # Remove leftover braces that often come from simple LaTeX snippets.
    text = text.replace("{", "").replace("}", "")
    return text


def polish_summary_text(summary: str) -> str:
    """
    Clean model output so it looks like a real study document, not a chatbot answer.

    Keeps Markdown headings (#, ##, ###) because the PDF generator uses them,
    but removes conversational preambles and noisy inline markdown markers.
    """
    text = summary.replace("\r\n", "\n").replace("\r", "\n").strip()
    if not text:
        return text

    raw_lines = text.split("\n")

    # Drop leading chatbot preambles such as "Absolument ! Voici...".
    while raw_lines and (not raw_lines[0].strip() or PREAMBLE_RE.match(raw_lines[0].strip())):
        raw_lines.pop(0)

    cleaned: list[str] = []
    inside_code_block = False

    for raw_line in raw_lines:
        line = raw_line.strip()

        if line.startswith("```"):
            inside_code_block = not inside_code_block
            continue

        if not line:
            cleaned.append("")
            continue

        if not inside_code_block:
            # Normalize bullet markers generated by Gemini.
            if line.startswith("* "):
                line = "- " + line[2:].strip()
            if line.startswith("• "):
                line = "- " + line[2:].strip()

            # Remove visible markdown bold/italic markers from API output/PDF source.
            line = line.replace("**", "")
            line = line.replace("__", "")

            # Avoid escaped markdown leftovers.
            line = re.sub(r"(?<!\*)\*(?!\*)", "", line)

            line = _clean_formula_markup(line)

        cleaned.append(line)

    # Collapse more than two empty lines.
    text = "\n".join(cleaned).strip()
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text
